//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE_HarrysWeb_V001.MobileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MobileService.MobileSoap")]
    public interface MobileSoap {
        
        // CODEGEN: Generating message contract since element name sUserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MGet_Login", ReplyAction="*")]
        AE_HarrysWeb_V001.MobileService.MGet_LoginResponse MGet_Login(AE_HarrysWeb_V001.MobileService.MGet_LoginRequest request);
        
        // CODEGEN: Generating message contract since element name sUserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MGet_UserAcknowledgement", ReplyAction="*")]
        AE_HarrysWeb_V001.MobileService.MGet_UserAcknowledgementResponse MGet_UserAcknowledgement(AE_HarrysWeb_V001.MobileService.MGet_UserAcknowledgementRequest request);
        
        // CODEGEN: Generating message contract since element name sUserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MGet_OutletList", ReplyAction="*")]
        AE_HarrysWeb_V001.MobileService.MGet_OutletListResponse MGet_OutletList(AE_HarrysWeb_V001.MobileService.MGet_OutletListRequest request);
        
        // CODEGEN: Generating message contract since element name MGet_CompanyListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MGet_CompanyList", ReplyAction="*")]
        AE_HarrysWeb_V001.MobileService.MGet_CompanyListResponse MGet_CompanyList(AE_HarrysWeb_V001.MobileService.MGet_CompanyListRequest request);
        
        // CODEGEN: Generating message contract since element name sCompanyDB from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MGet_InventoryRequest", ReplyAction="*")]
        AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestResponse MGet_InventoryRequest(AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestRequest request);
        
        // CODEGEN: Generating message contract since element name sCompanyDB from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MGet_InventoryRequestDetails", ReplyAction="*")]
        AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestDetailsResponse MGet_InventoryRequestDetails(AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name sCompanyDB from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MGet_OpenPOList", ReplyAction="*")]
        AE_HarrysWeb_V001.MobileService.MGet_OpenPOListResponse MGet_OpenPOList(AE_HarrysWeb_V001.MobileService.MGet_OpenPOListRequest request);
        
        // CODEGEN: Generating message contract since element name sCompanyDB from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MGet_ReceiveInOutlet_Details", ReplyAction="*")]
        AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutlet_DetailsResponse MGet_ReceiveInOutlet_Details(AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutlet_DetailsRequest request);
        
        // CODEGEN: Generating message contract since element name sCompanyDB from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MGet_ReasonCode", ReplyAction="*")]
        AE_HarrysWeb_V001.MobileService.MGet_ReasonCodeResponse MGet_ReasonCode(AE_HarrysWeb_V001.MobileService.MGet_ReasonCodeRequest request);
        
        // CODEGEN: Generating message contract since element name sCompanyDB from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MGet_ReceiveInOutlet", ReplyAction="*")]
        AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutletResponse MGet_ReceiveInOutlet(AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutletRequest request);
        
        // CODEGEN: Generating message contract since element name sCompanyDB from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MGet_ReceiveInVAN", ReplyAction="*")]
        AE_HarrysWeb_V001.MobileService.MGet_ReceiveInVANResponse MGet_ReceiveInVAN(AE_HarrysWeb_V001.MobileService.MGet_ReceiveInVANRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_Login", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_LoginRequestBody Body;
        
        public MGet_LoginRequest() {
        }
        
        public MGet_LoginRequest(AE_HarrysWeb_V001.MobileService.MGet_LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sCompanyDB;
        
        public MGet_LoginRequestBody() {
        }
        
        public MGet_LoginRequestBody(string sUserName, string sPassword, string sCompanyDB) {
            this.sUserName = sUserName;
            this.sPassword = sPassword;
            this.sCompanyDB = sCompanyDB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_LoginResponseBody Body;
        
        public MGet_LoginResponse() {
        }
        
        public MGet_LoginResponse(AE_HarrysWeb_V001.MobileService.MGet_LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MGet_LoginResult;
        
        public MGet_LoginResponseBody() {
        }
        
        public MGet_LoginResponseBody(string MGet_LoginResult) {
            this.MGet_LoginResult = MGet_LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_UserAcknowledgementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_UserAcknowledgement", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_UserAcknowledgementRequestBody Body;
        
        public MGet_UserAcknowledgementRequest() {
        }
        
        public MGet_UserAcknowledgementRequest(AE_HarrysWeb_V001.MobileService.MGet_UserAcknowledgementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_UserAcknowledgementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sOutlet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sCompanyDB;
        
        public MGet_UserAcknowledgementRequestBody() {
        }
        
        public MGet_UserAcknowledgementRequestBody(string sUserName, string sPassword, string sOutlet, string sCompanyDB) {
            this.sUserName = sUserName;
            this.sPassword = sPassword;
            this.sOutlet = sOutlet;
            this.sCompanyDB = sCompanyDB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_UserAcknowledgementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_UserAcknowledgementResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_UserAcknowledgementResponseBody Body;
        
        public MGet_UserAcknowledgementResponse() {
        }
        
        public MGet_UserAcknowledgementResponse(AE_HarrysWeb_V001.MobileService.MGet_UserAcknowledgementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_UserAcknowledgementResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MGet_UserAcknowledgementResult;
        
        public MGet_UserAcknowledgementResponseBody() {
        }
        
        public MGet_UserAcknowledgementResponseBody(string MGet_UserAcknowledgementResult) {
            this.MGet_UserAcknowledgementResult = MGet_UserAcknowledgementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_OutletListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_OutletList", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_OutletListRequestBody Body;
        
        public MGet_OutletListRequest() {
        }
        
        public MGet_OutletListRequest(AE_HarrysWeb_V001.MobileService.MGet_OutletListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_OutletListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sCompanyDB;
        
        public MGet_OutletListRequestBody() {
        }
        
        public MGet_OutletListRequestBody(string sUserName, string sPassword, string sCompanyDB) {
            this.sUserName = sUserName;
            this.sPassword = sPassword;
            this.sCompanyDB = sCompanyDB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_OutletListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_OutletListResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_OutletListResponseBody Body;
        
        public MGet_OutletListResponse() {
        }
        
        public MGet_OutletListResponse(AE_HarrysWeb_V001.MobileService.MGet_OutletListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_OutletListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MGet_OutletListResult;
        
        public MGet_OutletListResponseBody() {
        }
        
        public MGet_OutletListResponseBody(string MGet_OutletListResult) {
            this.MGet_OutletListResult = MGet_OutletListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_CompanyListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_CompanyList", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_CompanyListRequestBody Body;
        
        public MGet_CompanyListRequest() {
        }
        
        public MGet_CompanyListRequest(AE_HarrysWeb_V001.MobileService.MGet_CompanyListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MGet_CompanyListRequestBody {
        
        public MGet_CompanyListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_CompanyListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_CompanyListResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_CompanyListResponseBody Body;
        
        public MGet_CompanyListResponse() {
        }
        
        public MGet_CompanyListResponse(AE_HarrysWeb_V001.MobileService.MGet_CompanyListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_CompanyListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MGet_CompanyListResult;
        
        public MGet_CompanyListResponseBody() {
        }
        
        public MGet_CompanyListResponseBody(string MGet_CompanyListResult) {
            this.MGet_CompanyListResult = MGet_CompanyListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_InventoryRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_InventoryRequest", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestRequestBody Body;
        
        public MGet_InventoryRequestRequest() {
        }
        
        public MGet_InventoryRequestRequest(AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_InventoryRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCompanyDB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sOutlet;
        
        public MGet_InventoryRequestRequestBody() {
        }
        
        public MGet_InventoryRequestRequestBody(string sCompanyDB, string sOutlet) {
            this.sCompanyDB = sCompanyDB;
            this.sOutlet = sOutlet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_InventoryRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_InventoryRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestResponseBody Body;
        
        public MGet_InventoryRequestResponse() {
        }
        
        public MGet_InventoryRequestResponse(AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_InventoryRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MGet_InventoryRequestResult;
        
        public MGet_InventoryRequestResponseBody() {
        }
        
        public MGet_InventoryRequestResponseBody(string MGet_InventoryRequestResult) {
            this.MGet_InventoryRequestResult = MGet_InventoryRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_InventoryRequestDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_InventoryRequestDetails", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestDetailsRequestBody Body;
        
        public MGet_InventoryRequestDetailsRequest() {
        }
        
        public MGet_InventoryRequestDetailsRequest(AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_InventoryRequestDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCompanyDB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sRequestNo;
        
        public MGet_InventoryRequestDetailsRequestBody() {
        }
        
        public MGet_InventoryRequestDetailsRequestBody(string sCompanyDB, string sRequestNo) {
            this.sCompanyDB = sCompanyDB;
            this.sRequestNo = sRequestNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_InventoryRequestDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_InventoryRequestDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestDetailsResponseBody Body;
        
        public MGet_InventoryRequestDetailsResponse() {
        }
        
        public MGet_InventoryRequestDetailsResponse(AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_InventoryRequestDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MGet_InventoryRequestDetailsResult;
        
        public MGet_InventoryRequestDetailsResponseBody() {
        }
        
        public MGet_InventoryRequestDetailsResponseBody(string MGet_InventoryRequestDetailsResult) {
            this.MGet_InventoryRequestDetailsResult = MGet_InventoryRequestDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_OpenPOListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_OpenPOList", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_OpenPOListRequestBody Body;
        
        public MGet_OpenPOListRequest() {
        }
        
        public MGet_OpenPOListRequest(AE_HarrysWeb_V001.MobileService.MGet_OpenPOListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_OpenPOListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCompanyDB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sSupplier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sSupplierType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sAccessType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sOutlet;
        
        public MGet_OpenPOListRequestBody() {
        }
        
        public MGet_OpenPOListRequestBody(string sCompanyDB, string sSupplier, string sSupplierType, string sAccessType, string sOutlet) {
            this.sCompanyDB = sCompanyDB;
            this.sSupplier = sSupplier;
            this.sSupplierType = sSupplierType;
            this.sAccessType = sAccessType;
            this.sOutlet = sOutlet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_OpenPOListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_OpenPOListResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_OpenPOListResponseBody Body;
        
        public MGet_OpenPOListResponse() {
        }
        
        public MGet_OpenPOListResponse(AE_HarrysWeb_V001.MobileService.MGet_OpenPOListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_OpenPOListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MGet_OpenPOListResult;
        
        public MGet_OpenPOListResponseBody() {
        }
        
        public MGet_OpenPOListResponseBody(string MGet_OpenPOListResult) {
            this.MGet_OpenPOListResult = MGet_OpenPOListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_ReceiveInOutlet_DetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_ReceiveInOutlet_Details", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutlet_DetailsRequestBody Body;
        
        public MGet_ReceiveInOutlet_DetailsRequest() {
        }
        
        public MGet_ReceiveInOutlet_DetailsRequest(AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutlet_DetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_ReceiveInOutlet_DetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCompanyDB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sOutlet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sAccessType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sSupplier;
        
        public MGet_ReceiveInOutlet_DetailsRequestBody() {
        }
        
        public MGet_ReceiveInOutlet_DetailsRequestBody(string sCompanyDB, string sOutlet, string sAccessType, string sSupplier) {
            this.sCompanyDB = sCompanyDB;
            this.sOutlet = sOutlet;
            this.sAccessType = sAccessType;
            this.sSupplier = sSupplier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_ReceiveInOutlet_DetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_ReceiveInOutlet_DetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutlet_DetailsResponseBody Body;
        
        public MGet_ReceiveInOutlet_DetailsResponse() {
        }
        
        public MGet_ReceiveInOutlet_DetailsResponse(AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutlet_DetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_ReceiveInOutlet_DetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MGet_ReceiveInOutlet_DetailsResult;
        
        public MGet_ReceiveInOutlet_DetailsResponseBody() {
        }
        
        public MGet_ReceiveInOutlet_DetailsResponseBody(string MGet_ReceiveInOutlet_DetailsResult) {
            this.MGet_ReceiveInOutlet_DetailsResult = MGet_ReceiveInOutlet_DetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_ReasonCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_ReasonCode", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_ReasonCodeRequestBody Body;
        
        public MGet_ReasonCodeRequest() {
        }
        
        public MGet_ReasonCodeRequest(AE_HarrysWeb_V001.MobileService.MGet_ReasonCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_ReasonCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCompanyDB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sOutlet;
        
        public MGet_ReasonCodeRequestBody() {
        }
        
        public MGet_ReasonCodeRequestBody(string sCompanyDB, string sOutlet) {
            this.sCompanyDB = sCompanyDB;
            this.sOutlet = sOutlet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_ReasonCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_ReasonCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_ReasonCodeResponseBody Body;
        
        public MGet_ReasonCodeResponse() {
        }
        
        public MGet_ReasonCodeResponse(AE_HarrysWeb_V001.MobileService.MGet_ReasonCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_ReasonCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MGet_ReasonCodeResult;
        
        public MGet_ReasonCodeResponseBody() {
        }
        
        public MGet_ReasonCodeResponseBody(string MGet_ReasonCodeResult) {
            this.MGet_ReasonCodeResult = MGet_ReasonCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_ReceiveInOutletRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_ReceiveInOutlet", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutletRequestBody Body;
        
        public MGet_ReceiveInOutletRequest() {
        }
        
        public MGet_ReceiveInOutletRequest(AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutletRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_ReceiveInOutletRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCompanyDB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sJSONFile;
        
        public MGet_ReceiveInOutletRequestBody() {
        }
        
        public MGet_ReceiveInOutletRequestBody(string sCompanyDB, string sJSONFile) {
            this.sCompanyDB = sCompanyDB;
            this.sJSONFile = sJSONFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_ReceiveInOutletResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_ReceiveInOutletResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutletResponseBody Body;
        
        public MGet_ReceiveInOutletResponse() {
        }
        
        public MGet_ReceiveInOutletResponse(AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutletResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_ReceiveInOutletResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MGet_ReceiveInOutletResult;
        
        public MGet_ReceiveInOutletResponseBody() {
        }
        
        public MGet_ReceiveInOutletResponseBody(string MGet_ReceiveInOutletResult) {
            this.MGet_ReceiveInOutletResult = MGet_ReceiveInOutletResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_ReceiveInVANRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_ReceiveInVAN", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_ReceiveInVANRequestBody Body;
        
        public MGet_ReceiveInVANRequest() {
        }
        
        public MGet_ReceiveInVANRequest(AE_HarrysWeb_V001.MobileService.MGet_ReceiveInVANRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_ReceiveInVANRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCompanyDB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sJSONFile;
        
        public MGet_ReceiveInVANRequestBody() {
        }
        
        public MGet_ReceiveInVANRequestBody(string sCompanyDB, string sJSONFile) {
            this.sCompanyDB = sCompanyDB;
            this.sJSONFile = sJSONFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MGet_ReceiveInVANResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MGet_ReceiveInVANResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_HarrysWeb_V001.MobileService.MGet_ReceiveInVANResponseBody Body;
        
        public MGet_ReceiveInVANResponse() {
        }
        
        public MGet_ReceiveInVANResponse(AE_HarrysWeb_V001.MobileService.MGet_ReceiveInVANResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MGet_ReceiveInVANResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MGet_ReceiveInVANResult;
        
        public MGet_ReceiveInVANResponseBody() {
        }
        
        public MGet_ReceiveInVANResponseBody(string MGet_ReceiveInVANResult) {
            this.MGet_ReceiveInVANResult = MGet_ReceiveInVANResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MobileSoapChannel : AE_HarrysWeb_V001.MobileService.MobileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobileSoapClient : System.ServiceModel.ClientBase<AE_HarrysWeb_V001.MobileService.MobileSoap>, AE_HarrysWeb_V001.MobileService.MobileSoap {
        
        public MobileSoapClient() {
        }
        
        public MobileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_HarrysWeb_V001.MobileService.MGet_LoginResponse AE_HarrysWeb_V001.MobileService.MobileSoap.MGet_Login(AE_HarrysWeb_V001.MobileService.MGet_LoginRequest request) {
            return base.Channel.MGet_Login(request);
        }
        
        public string MGet_Login(string sUserName, string sPassword, string sCompanyDB) {
            AE_HarrysWeb_V001.MobileService.MGet_LoginRequest inValue = new AE_HarrysWeb_V001.MobileService.MGet_LoginRequest();
            inValue.Body = new AE_HarrysWeb_V001.MobileService.MGet_LoginRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sCompanyDB = sCompanyDB;
            AE_HarrysWeb_V001.MobileService.MGet_LoginResponse retVal = ((AE_HarrysWeb_V001.MobileService.MobileSoap)(this)).MGet_Login(inValue);
            return retVal.Body.MGet_LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_HarrysWeb_V001.MobileService.MGet_UserAcknowledgementResponse AE_HarrysWeb_V001.MobileService.MobileSoap.MGet_UserAcknowledgement(AE_HarrysWeb_V001.MobileService.MGet_UserAcknowledgementRequest request) {
            return base.Channel.MGet_UserAcknowledgement(request);
        }
        
        public string MGet_UserAcknowledgement(string sUserName, string sPassword, string sOutlet, string sCompanyDB) {
            AE_HarrysWeb_V001.MobileService.MGet_UserAcknowledgementRequest inValue = new AE_HarrysWeb_V001.MobileService.MGet_UserAcknowledgementRequest();
            inValue.Body = new AE_HarrysWeb_V001.MobileService.MGet_UserAcknowledgementRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sOutlet = sOutlet;
            inValue.Body.sCompanyDB = sCompanyDB;
            AE_HarrysWeb_V001.MobileService.MGet_UserAcknowledgementResponse retVal = ((AE_HarrysWeb_V001.MobileService.MobileSoap)(this)).MGet_UserAcknowledgement(inValue);
            return retVal.Body.MGet_UserAcknowledgementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_HarrysWeb_V001.MobileService.MGet_OutletListResponse AE_HarrysWeb_V001.MobileService.MobileSoap.MGet_OutletList(AE_HarrysWeb_V001.MobileService.MGet_OutletListRequest request) {
            return base.Channel.MGet_OutletList(request);
        }
        
        public string MGet_OutletList(string sUserName, string sPassword, string sCompanyDB) {
            AE_HarrysWeb_V001.MobileService.MGet_OutletListRequest inValue = new AE_HarrysWeb_V001.MobileService.MGet_OutletListRequest();
            inValue.Body = new AE_HarrysWeb_V001.MobileService.MGet_OutletListRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sCompanyDB = sCompanyDB;
            AE_HarrysWeb_V001.MobileService.MGet_OutletListResponse retVal = ((AE_HarrysWeb_V001.MobileService.MobileSoap)(this)).MGet_OutletList(inValue);
            return retVal.Body.MGet_OutletListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_HarrysWeb_V001.MobileService.MGet_CompanyListResponse AE_HarrysWeb_V001.MobileService.MobileSoap.MGet_CompanyList(AE_HarrysWeb_V001.MobileService.MGet_CompanyListRequest request) {
            return base.Channel.MGet_CompanyList(request);
        }
        
        public string MGet_CompanyList() {
            AE_HarrysWeb_V001.MobileService.MGet_CompanyListRequest inValue = new AE_HarrysWeb_V001.MobileService.MGet_CompanyListRequest();
            inValue.Body = new AE_HarrysWeb_V001.MobileService.MGet_CompanyListRequestBody();
            AE_HarrysWeb_V001.MobileService.MGet_CompanyListResponse retVal = ((AE_HarrysWeb_V001.MobileService.MobileSoap)(this)).MGet_CompanyList(inValue);
            return retVal.Body.MGet_CompanyListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestResponse AE_HarrysWeb_V001.MobileService.MobileSoap.MGet_InventoryRequest(AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestRequest request) {
            return base.Channel.MGet_InventoryRequest(request);
        }
        
        public string MGet_InventoryRequest(string sCompanyDB, string sOutlet) {
            AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestRequest inValue = new AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestRequest();
            inValue.Body = new AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestRequestBody();
            inValue.Body.sCompanyDB = sCompanyDB;
            inValue.Body.sOutlet = sOutlet;
            AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestResponse retVal = ((AE_HarrysWeb_V001.MobileService.MobileSoap)(this)).MGet_InventoryRequest(inValue);
            return retVal.Body.MGet_InventoryRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestDetailsResponse AE_HarrysWeb_V001.MobileService.MobileSoap.MGet_InventoryRequestDetails(AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestDetailsRequest request) {
            return base.Channel.MGet_InventoryRequestDetails(request);
        }
        
        public string MGet_InventoryRequestDetails(string sCompanyDB, string sRequestNo) {
            AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestDetailsRequest inValue = new AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestDetailsRequest();
            inValue.Body = new AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestDetailsRequestBody();
            inValue.Body.sCompanyDB = sCompanyDB;
            inValue.Body.sRequestNo = sRequestNo;
            AE_HarrysWeb_V001.MobileService.MGet_InventoryRequestDetailsResponse retVal = ((AE_HarrysWeb_V001.MobileService.MobileSoap)(this)).MGet_InventoryRequestDetails(inValue);
            return retVal.Body.MGet_InventoryRequestDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_HarrysWeb_V001.MobileService.MGet_OpenPOListResponse AE_HarrysWeb_V001.MobileService.MobileSoap.MGet_OpenPOList(AE_HarrysWeb_V001.MobileService.MGet_OpenPOListRequest request) {
            return base.Channel.MGet_OpenPOList(request);
        }
        
        public string MGet_OpenPOList(string sCompanyDB, string sSupplier, string sSupplierType, string sAccessType, string sOutlet) {
            AE_HarrysWeb_V001.MobileService.MGet_OpenPOListRequest inValue = new AE_HarrysWeb_V001.MobileService.MGet_OpenPOListRequest();
            inValue.Body = new AE_HarrysWeb_V001.MobileService.MGet_OpenPOListRequestBody();
            inValue.Body.sCompanyDB = sCompanyDB;
            inValue.Body.sSupplier = sSupplier;
            inValue.Body.sSupplierType = sSupplierType;
            inValue.Body.sAccessType = sAccessType;
            inValue.Body.sOutlet = sOutlet;
            AE_HarrysWeb_V001.MobileService.MGet_OpenPOListResponse retVal = ((AE_HarrysWeb_V001.MobileService.MobileSoap)(this)).MGet_OpenPOList(inValue);
            return retVal.Body.MGet_OpenPOListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutlet_DetailsResponse AE_HarrysWeb_V001.MobileService.MobileSoap.MGet_ReceiveInOutlet_Details(AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutlet_DetailsRequest request) {
            return base.Channel.MGet_ReceiveInOutlet_Details(request);
        }
        
        public string MGet_ReceiveInOutlet_Details(string sCompanyDB, string sOutlet, string sAccessType, string sSupplier) {
            AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutlet_DetailsRequest inValue = new AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutlet_DetailsRequest();
            inValue.Body = new AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutlet_DetailsRequestBody();
            inValue.Body.sCompanyDB = sCompanyDB;
            inValue.Body.sOutlet = sOutlet;
            inValue.Body.sAccessType = sAccessType;
            inValue.Body.sSupplier = sSupplier;
            AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutlet_DetailsResponse retVal = ((AE_HarrysWeb_V001.MobileService.MobileSoap)(this)).MGet_ReceiveInOutlet_Details(inValue);
            return retVal.Body.MGet_ReceiveInOutlet_DetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_HarrysWeb_V001.MobileService.MGet_ReasonCodeResponse AE_HarrysWeb_V001.MobileService.MobileSoap.MGet_ReasonCode(AE_HarrysWeb_V001.MobileService.MGet_ReasonCodeRequest request) {
            return base.Channel.MGet_ReasonCode(request);
        }
        
        public string MGet_ReasonCode(string sCompanyDB, string sOutlet) {
            AE_HarrysWeb_V001.MobileService.MGet_ReasonCodeRequest inValue = new AE_HarrysWeb_V001.MobileService.MGet_ReasonCodeRequest();
            inValue.Body = new AE_HarrysWeb_V001.MobileService.MGet_ReasonCodeRequestBody();
            inValue.Body.sCompanyDB = sCompanyDB;
            inValue.Body.sOutlet = sOutlet;
            AE_HarrysWeb_V001.MobileService.MGet_ReasonCodeResponse retVal = ((AE_HarrysWeb_V001.MobileService.MobileSoap)(this)).MGet_ReasonCode(inValue);
            return retVal.Body.MGet_ReasonCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutletResponse AE_HarrysWeb_V001.MobileService.MobileSoap.MGet_ReceiveInOutlet(AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutletRequest request) {
            return base.Channel.MGet_ReceiveInOutlet(request);
        }
        
        public string MGet_ReceiveInOutlet(string sCompanyDB, string sJSONFile) {
            AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutletRequest inValue = new AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutletRequest();
            inValue.Body = new AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutletRequestBody();
            inValue.Body.sCompanyDB = sCompanyDB;
            inValue.Body.sJSONFile = sJSONFile;
            AE_HarrysWeb_V001.MobileService.MGet_ReceiveInOutletResponse retVal = ((AE_HarrysWeb_V001.MobileService.MobileSoap)(this)).MGet_ReceiveInOutlet(inValue);
            return retVal.Body.MGet_ReceiveInOutletResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_HarrysWeb_V001.MobileService.MGet_ReceiveInVANResponse AE_HarrysWeb_V001.MobileService.MobileSoap.MGet_ReceiveInVAN(AE_HarrysWeb_V001.MobileService.MGet_ReceiveInVANRequest request) {
            return base.Channel.MGet_ReceiveInVAN(request);
        }
        
        public string MGet_ReceiveInVAN(string sCompanyDB, string sJSONFile) {
            AE_HarrysWeb_V001.MobileService.MGet_ReceiveInVANRequest inValue = new AE_HarrysWeb_V001.MobileService.MGet_ReceiveInVANRequest();
            inValue.Body = new AE_HarrysWeb_V001.MobileService.MGet_ReceiveInVANRequestBody();
            inValue.Body.sCompanyDB = sCompanyDB;
            inValue.Body.sJSONFile = sJSONFile;
            AE_HarrysWeb_V001.MobileService.MGet_ReceiveInVANResponse retVal = ((AE_HarrysWeb_V001.MobileService.MobileSoap)(this)).MGet_ReceiveInVAN(inValue);
            return retVal.Body.MGet_ReceiveInVANResult;
        }
    }
}
